routes/web.php
<?php

use App\Http\Controllers\Admin\MessageController;
use App\Http\Controllers\Admin\Products\ComputerController;
use App\Http\Controllers\Admin\Products\EarphoneController;
use App\Http\Controllers\Admin\Products\TelephoneController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Livewire\Admin\Dashboard;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Front Routes
Route::get('/', function(){
    return view('front.welcome');
})->name('home');

    // Admin Routes
    Route::middleware([
        'auth:sanctum',
        config('jetstream.auth_session'),
        'verified'
    ])->group(function () {
        Route::middleware(['is_admin'])->group(function(){
            Route::prefix('admin')->group(function () {
                Route::name('admin.')->group(function () {
                    Route::get('/dashboard', Dashboard::class)->name('dashboard');
                    Route::get('/users', [UserController::class, 'index'])->name('users');
                    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
                    Route::resource('computers',ComputerController::class);
                    Route::resource('telephones',TelephoneController::class);
                    Route::resource('earphones',EarphoneController::class);
                    Route::controller(MessageController::class)->group(function () {
                        Route::get('/notifications', 'notifications')->name('notifications');
                        Route::get('/notify/{id}', 'notify')->name('notify');
                        Route::get('/markasread/{id}', 'markAsRead')->name('markasread');
                        Route::get('/markallasread', 'markAllAsRead')->name('markallasread');
                    });

                });
            });
        });



    });


Route::fallback(function () {
    return view('admin.components.error404');
});

app/Models/Computer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Computer extends Model
{
    use HasFactory;
    protected $fillable=[
        'name',
        'color',
        'price',
        'character',
        'img',
        'status',
    ];
}

app/Http/Controllers/Admin/Products/ComputerController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use App\Http\Controllers\Controller;
use App\Models\Computer;
use Illuminate\Http\Request;

class ComputerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
//     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        dd('a');
        $computers=Computer::orderByDesc('created_at')->paginate(5);

        return view('admin.products.computer.index',['products'=>$computers]);
    }

    /**
     * Show the form for creating a new resource.
     *
//     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.products.computer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
//     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Computer::create($this->validateData());

        return redirect()->route('admin.computers.index');



    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Computer  $computer
//     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $comp=Computer::find($id);
        return view('admin.products.computer.show',['product'=>$comp]);
    }

    /**
     * Show the form for editing the specified resource.
     *
//     * @param  \App\Models\computer  $computer
//     * @return \Illuminate\Http\Response
     */
    public function edit(Computer $computer)
    {
        return view('admin.products.computer.edit',[
            'product'=>$computer
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateComputerRequest  $request
     * @param  \App\Models\computer  $computer
//     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Computer $computer)
    {
        $computer->update($this->validateData());
        return redirect()->route('admin.computers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Computer  $computer
//     * @return \Illuminate\Http\Response
     */
    public function destroy(Computer $computer)
    {
//        dd('a');
        $computer->delete();
        return redirect()->route('admin.computers.index');
    }

    public function validateData()
    {
        return request()->validate([
            'name'=>'required',
            'color'=>'required',
            'img'=>'required',
            'character'=>'required',
            'price'=>'required',
            'status'=>'required'
        ]);

    }
}

app/Http/Controllers/Admin/Products/EarphoneController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreEarphoneRequest;
use App\Http\Requests\UpdateEarphoneRequest;
use App\Models\earphone;

class EarphoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreEarphoneRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEarphoneRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\earphone  $earphone
     * @return \Illuminate\Http\Response
     */
    public function show(earphone $earphone)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\earphone  $earphone
     * @return \Illuminate\Http\Response
     */
    public function edit(earphone $earphone)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateEarphoneRequest  $request
     * @param  \App\Models\earphone  $earphone
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEarphoneRequest $request, earphone $earphone)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\earphone  $earphone
     * @return \Illuminate\Http\Response
     */
    public function destroy(earphone $earphone)
    {
        //
    }
}

app/Http/Controllers/Admin/Products/TelephoneController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use App\Http\Controllers\Controller;
use App\Models\Telephone;
use Illuminate\Http\Request;

class TelephoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $telephones=Telephone::orderByDesc('created_at')->paginate(7);
        return view('telephone.index',['products'=>$telephones]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('telephone.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        Telephone::create($this->validateData());
        return redirect()->route('telephones.index');



    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Telephone  $Telephone
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $comp=Telephone::find($id);
        return view('telephone.show',['product'=>$comp]);
    }

    /**
     * Show the form for editing the specified resource.
     *
    //     * @param  \App\Models\Telephone  $Telephone
    //     * @return \Illuminate\Http\Response
     */
    public function edit(Telephone $telephone)
    {
        return view('telephone.edit',[
            'product'=>$telephone
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateTelephoneRequest  $request
     * @param  \App\Models\Telephone  $Telephone
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Telephone $telephone)
    {
        $telephone->update($this->validateData());
        return redirect()->route('telephones.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Telephone  $Telephone
     * @return \Illuminate\Http\Response
     */
    public function destroy(Telephone $telephone)
    {
        $telephone->delete();
        return redirect()->route('telephones.index');
    }

    public function validateData()
    {
        return request()->validate([
            'name'=>'required',
            'color'=>'required',
            'img'=>'required',
            'character'=>'required',
            'price'=>'required',
            'status'=>'required'
        ]);

    }
}

resources/views/admin/products/computer/create.blade.php
@extends('layouts.admin')
@section('content')
    <h1 class="text-center p-3">{{__('Create Item')}}</h1>
    <div class="row d-flex justify-content-center">
        <div class="col-md-4">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{route('admin.computers.store')}}">
                @csrf
                <div class="mb-3">
                    <label for="name" class="form-label">{{__('Computer name')}}</label>
                    <input type="text" class="form-control" id="name" name="name"  value="{{old('name')}}">
                </div>
                <div class="mb-3">
                    <label for="color" class="form-label">{{__('Color')}}</label>
                    <input type="text" class="form-control" id="color" name="color" value="{{old('color')}}">
                </div>
                <div class="mb-3">
                    <label for="price" class="form-label">{{__('Price')}}</label>
                    <input type="text" class="form-control" id="price" name="price" value="{{old('price')}}">
                </div>
                <div class="mb-3">
{{--                    <label for="character" class="form-label">{{__('Character')}}</label><br>--}}
                    <textarea name="character" placeholder="character..." cols="57" rows="5"></textarea>
                </div>
                <div class="mb-3">
                    <label for="image" class="form-label">{{__('Image')}}</label>
                    <input type="file" class="form-control" id="image" name="img" value="{{old('image')}}">

                </div>
                <div class="mb-5">
                    <label for="stat" class="form-label">{{__('Status')}}</label>
                    <select class="form-select" aria-label="Default select example">
                        <option selected value="1">active</option>
                        <option value="2">inactive</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary">{{__('Submit')}}</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/products/computer/edit.blade.php
@extends('layouts.admin')
@section('content')
    <h1 class="text-center p-3">{{__('Update Item')}}</h1>
    <div class="row">
        <div class="col-md-6">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{route('admin.computers.update',$product->id)}}">
                @method('PUT')
                @csrf
                <div class="mb-3">
                    <label for="name" class="form-label">{{__('Computer name')}}</label>
                    <input type="text" class="form-control" id="name" name="name"  value="{{$product->name}}">
                </div>
                <div class="mb-3">
                    <label for="color" class="form-label">{{__('Color')}}</label>
                    <input type="text" class="form-control" id="color" name="color" value="{{$product->color}}">
                </div>
                <div class="mb-3">
                    <label for="price" class="form-label">{{__('Price')}}</label>
                    <input type="text" class="form-control" id="price" name="price" value="{{$product->price}}">
                </div>
                <div class="mb-3">
                    <label for="character" class="form-label">{{__('Character')}}</label>
                    <input type="text" class="form-control" id="character" name="character" value="{{$product->character}}">
                </div>
                <div class="mb-3">
                    <label for="image" class="form-label">{{__('Image')}}</label>
                    <input type="text" class="form-control" id="image" name="img" value="{{$product->img}}">
                </div>
                <div class="mb-3">
                    <label for="status" class="form-label">{{__('Status')}}</label>
                    <input type="text" class="form-control" id="status" name="status" value="{{$product->status}}">
                </div>
                <button type="submit" class="btn btn-primary">{{__('Update')}}</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/products/computer/index.blade.php
@extends('layouts.admin ')
@section('content')
    <div class="container">
        <table class="table">
            <caption>List of computers</caption>
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">{{_('name')}}</th>
                <th scope="col">{{__('Image')}}</th>
                <th scope="col">{{__('Color')}}</th>
                <th scope="col">{{__('Character')}}</th>
                <th scope="col">{{__('Price')}}</th>
                <th scope="col">{{__('Status')}}</th>
                <th colspan="3" class="text-center" scope="col">{{__('Actions')}}</th>

            </tr>
            </thead>
            <tbody>
            <div class="d-flex flex-row-reverse"><a href="{{route('admin.computers.create')}}" class="btn bg-primary text-white m-3 ">{{__('Add Item')}}</a></div>
            @foreach($products as $product)
                <tr>
                    <th scope="row">{{($products->currentpage()-1)*$products->perpage()+$loop->index+1}}</th>
                    <td>{{$product->name}}</td>
                    <td style="width: 100px; height: 100px;"><img style="width: 100%; height: 100%;"  src="./images/notebook/mbp-silver-select-202011_result-500x500.jpeg"></td>
                    <td>{{$product->color}}</td>
                    <td>{{$product->character}}</td>
                    <td>{{$product->price}}</td>
                    <td>{{$product->status}}</td>
                    <td>
                        <a href="{{route('admin.computers.show',$product->id)}}">
                            <i class="fa fa-eye"  aria-hidden="true"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{{route('admin.computers.edit',['computer'=>$product->id])}}">
                            <i class="fas fa-pencil-alt" aria-hidden="true"></i>
                        </a>
                    </td>
                    <td>
                        <form method="post" action="{{route('admin.computers.destroy',['computer'=>$product->id])}}">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-danger">

                                <i class="fas fa-trash-alt" aria-hidden="true"></i>
                            </button>

                        </form>

                    </td>
                </tr>
            @endforeach
            </tbody>

        </table>

        {{$products->links()}}
    </div>
@endsection

resources/views/admin/products/computer/show.blade.php
@extends('layouts.app')
@section('content')
    <h1 class="text-center p-3">Information about computer</h1>
    <div class="container border row d-flex align-items-center " style="height: 60vh">
        <div class="img col-md-5 d-flex justify-content-center" style="height: 50%">
            <img style="height: 100%" src="../images/notebook/mbp-silver-select-202011_result-500x500.jpeg" alt="">
        </div>
        <div class="col-md-6 d-flex align-items-center " style="height: 50%">
            <table class="table table-bordered">
                <tr>
                    <td>{{__('Computer Name')}}</td>
                    <td>{{$product->name}}</td>
                </tr>
                <tr>
                    <td>{{__('Computer color')}}</td>
                    <td>{{$product->color}}</td>
                </tr>
                <tr>
                    <td>{{__('Computer character')}}</td>
                    <td>{{$product->character}}</td>
                </tr>
                <tr>
                    <td>{{__('Computer price')}}</td>
                    <td>{{$product->price}}</td>
                </tr>
                <tr>
                    <td>{{__('On sale')}}</td>
                    <td>{{$product->status}}</td>
                </tr>
            </table>
        </div>
    </div>
@endsection